# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
platform_plugin_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "platform"))
if os.path.isdir(platform_plugin_path):
    os.environ.setdefault("QT_QPA_PLATFORM_PLUGIN_PATH", platform_plugin_path)
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 520)
        MainWindow.setMinimumSize(QtCore.QSize(860, 520))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Titlename = QtWidgets.QLabel(self.centralwidget)
        self.Titlename.setGeometry(QtCore.QRect(0, 10, 860, 45))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.Titlename.setFont(font)
        self.Titlename.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlename.setObjectName("Titlename")
        self.btn_en = QtWidgets.QPushButton(self.centralwidget)
        self.btn_en.setGeometry(QtCore.QRect(220, 400, 120, 32))
        self.btn_en.setObjectName("btn_en")
        self.txt_banro = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_banro.setGeometry(QtCore.QRect(280, 70, 460, 130))
        self.txt_banro.setObjectName("txt_banro")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 75, 220, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txt_key = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_key.setGeometry(QtCore.QRect(280, 220, 460, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_key.setFont(font)
        self.txt_key.setObjectName("txt_key")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 224, 220, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 275, 220, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txt_banma = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_banma.setGeometry(QtCore.QRect(280, 270, 460, 105))
        self.txt_banma.setObjectName("txt_banma")
        self.btn_de = QtWidgets.QPushButton(self.centralwidget)
        self.btn_de.setGeometry(QtCore.QRect(500, 400, 120, 32))
        self.btn_de.setObjectName("btn_de")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Caesar Cipher"))
        self.Titlename.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.btn_en.setText(_translate("MainWindow", "Encrypt"))
        self.label.setText(_translate("MainWindow", "Plain Text"))
        self.label_2.setText(_translate("MainWindow", "Key"))
        self.label_3.setText(_translate("MainWindow", "Cipher Text"))
        self.btn_de.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
